### ISSUE TITLE
App opens as white page

### ISSUE THREAD

**Issue by dr460nf1r3** [meetrevision/revision-tool#65]
The Revision Tool opens as a white page instead of showing the page content.

Version: the one preinstalled with ReviOS and after updating now, the latest `1.6.2`

Sadly no logs were produced when running the exe via the command line. How do we provide debugging information?

**Comment by melo936** [comment]
Please send logs from `%temp%\Revision-Tool\Logs`

**Comment by dr460nf1r3** [comment]
Here we go: 
~~~
2023-12-09 14:00:26.194 [I] Revision Tool is starting
2023-12-09 14:00:26.195 [W] Error reading ThemeMode from localMachine SOFTWARE\Revision\Revision Tool
2023-12-09 14:00:26.195 [I] Creating Revision registry keys
2023-12-09 14:00:26.195 [I] Initializing settings controller
2023-12-09 14:00:26.197 [I] Initializing WindowPlus
2023-12-09 14:00:26.401 [I] isSupported is true
2023-12-09 14:00:35.376 [E] Error: 
FileSystemException: writeFrom failed, path = '' (OS Error: The handle is invalid.
, errno = 6)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:904)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#8      _StreamController._add (dart:async/stream_controller.dart:658)
#9      _StreamController.add (dart:async/stream_controller.dart:606)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
#11     _StdSink.add (dart:io/stdio.dart:350)
#12     streamSinkWrite (package:process_run/src/shell_utils_common.dart:31)
#13     streamSinkWriteln (package:process_run/src/shell_utils_common.dart:24)
#14     processCmdRun (package:process_run/src/process_run.dart:214)
#15     Shell._lockedRunExecutableArguments.run (package:process_run/src/shell.dart:409)
#16     Shell._lockedRunExecutableArguments (package:process_run/src/shell.dart:472)
#17     Shell.run.<anonymous closure> (package:process_run/src/shell.dart:322)
#18     Shell._runLocked.<anonymous closure> (package:process_run/src/shell.dart:354)
#19     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31)
#20     Shell._runLocked (package:process_run/src/shell.dart:352)
#21     Shell.run (package:process_run/src/shell.dart:295)
#22     SecurityService.enableDefender (package:revitool/services/security_service.dart:44)
#23     _SecurityPageState.build.<anonymous closure> (package:revitool/screens/pages/security_page.dart:61)
#24     CardHighlightSwitch.build.<anonymous closure>.<anonymous closure> (package:revitool/widgets/card_highlight.dart:92)
#25     _ToggleSwitchState.build.<anonymous closure> (package:fluent_ui/src/controls/inputs/toggle_switch.dart:146)
#26     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#27     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
#28     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
#29     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281)
#30     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#31     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#32     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#33     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333)
#34     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#35     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#36     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#37     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#38     _rootRunUnary (dart:async/zone.dart:1415)
#39     _CustomZone.runUnary (dart:async/zone.dart:1308)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#41     _invoke1 (dart:ui/hooks.dart:188)
#42     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424)
#43     _dispatchPointerDataPacket (dart:ui/hooks.dart:119)



2023-12-09 14:00:40.191 [W] Error reading binary Scancode Map from SYSTEM\CurrentControlSet\Control\Keyboard Layout
2023-12-09 14:00:46.111 [W] Error reading EnabledState from localMachine SYSTEM\ControlSet001\Control\FeatureManagement\Overrides\8\1931258509
2023-12-09 14:00:53.508 [W] Error reading DirectXUserGlobalSettings from currentUser Software\Microsoft\DirectX\UserGpuPreferences
2023-12-09 14:00:53.508 [W] Error reading LetAppsRunInBackground from localMachine Software\Policies\Microsoft\Windows\AppPrivacy
2023-12-09 14:01:08.756 [W] Error reading Capabilities from localMachine SYSTEM\ControlSet001\Control\Processor
2023-12-09 14:01:21.243 [E] Error: 
ShellException(sc start GraphicsPerfSvc, exitCode 1058, workingDirectory: C:\Program Files (x86)\Revision Tool)



2023-12-10 17:09:46.467 [I] Revision Tool is starting
2023-12-10 17:09:46.469 [I] Initializing settings controller
2023-12-10 17:09:46.473 [I] Initializing WindowPlus
2023-12-10 17:09:46.684 [I] isSupported is true

**Comment by melo936** [comment]
Could you test [1.6.3](https://github.com/meetrevision/revision-tool/releases/tag/1.6.3)? Also have you done any post-modification before or after using ReviOS Playbook?

**Comment by dr460nf1r3** [comment]
Thanks for the update. I tested 1.6.3 and the following pre-release versions, sadly I still get the same white page. No post-modifications other than installing Chocolatey, drivers & applications. Shall I provide updated logfiles?

**Comment by melo936** [comment]
Have you made any post modifications after applying the ReviOS Playbook? Also, could you provide details about your computer specs? 

If you have a Discord account, it would be nice to communicate there. Here is our server link: https://discord.gg/962y4pU.

**Comment by dwonderg** [comment]
Same problem on install with 22H2
